# Generated by Django 5.1.2 on 2024-10-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_uri", models.TextField(blank=True)),
                ("client_id", models.TextField(blank=True)),
                ("client_secret", models.TextField(blank=True)),
                ("scopes", models.TextField(blank=True)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
