# Generated by Django 5.1.2 on 2024-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailaccount",
            name="shared",
            field=models.BooleanField(default=False),
        ),
    ]
