# Generated by Django 5.1.2 on 2024-10-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetch", "0002_gmailaccount_shared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmailaccount",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
